
title: Computational Neuroimaging and Brain Disorders
url: 'http://www.hongseokjun.com'
baseurl: '/academic_cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Seok-Jun Hong
tagline: Post-doctoral fellow in MNI
pic: me.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: sjhong@bic.mni.mcgill.ca
phone: 514 398 2906
Lab website: mica-mni.github.io
google scholar: https://scholar.google.com/citations?user=N7uX1isAAAAJ&hl=en
twitter: '@webjeda'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
